#!/usr/bin/env bash
# Pin requirements.in and its dependencies into requirements.txt, with the sha256 of every
# aarch64 Linux wheel of each pin for CPython 3.12 to 3.14: the installer runs
# pip install --require-hashes, and a SteamOS update may bring a newer Python.
# Run it on the Frame (or any aarch64 Linux with Python 3.12) after changing requirements.in.
set -euo pipefail
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

python3 -m venv "$work/venv"
"$work/venv/bin/pip" install -q --disable-pip-version-check -r "$root/requirements.in"
"$work/venv/bin/pip" freeze --all --exclude pip --exclude setuptools > "$work/pins.txt"

for py in 3.12 3.13 3.14; do
  abi=cp${py/./}
  if ! "$work/venv/bin/pip" download -q --disable-pip-version-check --no-deps --only-binary=:all: \
      --implementation cp --python-version "$py" --abi "$abi" --abi abi3 --abi none \
      --platform manylinux_2_39_aarch64 --platform manylinux_2_34_aarch64 --platform manylinux_2_28_aarch64 \
      --platform manylinux_2_17_aarch64 --platform manylinux2014_aarch64 --platform any \
      -d "$work/wheels" -r "$work/pins.txt"; then
    echo "warning: not every pin has a wheel for Python $py: no hashes for it" >&2
  fi
done

python3 - "$work/pins.txt" "$work/wheels" > "$root/requirements.txt" <<'EOF'
import hashlib, os, re, sys
pins, wheels = sys.argv[1], sys.argv[2]
norm = lambda s: re.sub(r"[-_.]+", "_", s).lower()
files = {}
for name in sorted(os.listdir(wheels)):
    dist = norm(name.split("-")[0])
    with open(os.path.join(wheels, name), "rb") as f:
        files.setdefault(dist, set()).add(hashlib.sha256(f.read()).hexdigest())
print("# Generated by scripts/lock-requirements.sh from requirements.in: don't edit by hand.")
for line in open(pins):
    line = line.strip()
    if not line:
        continue
    dist = norm(line.split("==")[0])
    hashes = sorted(files.get(dist, ()))
    if not hashes:
        sys.exit(f"no wheel downloaded for {line}")
    print(line + " \\")
    print(" \\\n".join("    --hash=sha256:" + h for h in hashes))
EOF
echo "wrote requirements.txt ($(grep -c '==' "$root/requirements.txt") pins)"
